nelmio_api_doc:
    documentation:
        info:
            title: FastSpeak REST API
            description: Rest api con todas las funcionalidades de nuestra aplicación
            version: 1.0.0
        components:
            securitySchemes:
                ApiKey:
                    type: apiKey
                    scheme: bearer
                    name: apiKey
                    bearerFormat: JWT
                    in: header
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
