nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'token', 'id', 'comunidad', 'voto', 'publicacion',
                        'idPerfil', 'usuarioPerfil', 'followUsuario', 'followComunidad','eliminarComentarioID']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
